import { expect, test } from '@playwright/test'

test('刪除需確認、可取消，名單保留並能還原', async ({ page }, testInfo) => {
  const name = `合成刪除確認-${testInfo.project.name}`
  await page.goto('/admin/competitions')
  await page.getByLabel('帳號', { exact: true }).fill('e2e-deletion-admin')
  await page.getByLabel('密碼', { exact: true }).fill(process.env.FUCHENG_E2E_ADMIN_PASSWORD!)
  await page.getByRole('button', { name: '登入', exact: true }).click()
  await expect(page.getByRole('heading', { name: '比賽', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '建立比賽', exact: true }).click()
  await page.getByLabel('名稱', { exact: true }).fill(name)
  await page.getByLabel('比賽日期', { exact: true }).fill('2099-09-20')
  await page.getByLabel('名額上限').fill('3')
  await page.getByLabel('報名截止時間（台北時間）').fill('2099-09-19T12:00')
  await page.getByRole('combobox', { name: '狀態' }).selectOption('open')
  await page.getByRole('button', { name: '儲存比賽', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('比賽已建立')
  const me = await (await page.request.get('/api/auth/me')).json()
  const headers = { 'X-CSRF-Token': me.csrf_token }
  const comps = await (await page.request.get('/api/admin/competitions')).json()
  const competition = comps.find((c: { name: string }) => c.name === name)
  const member = await (await page.request.post('/api/admin/members', { headers, data: {
    name: `${name}選手`, level: 3, diet: 'vegetarian', is_active: true,
  } })).json()
  const added = await page.request.post(`/api/admin/competitions/${competition.id}/registrations`, { headers, data: { member_id: member.id, request_id: crypto.randomUUID() } })
  expect(added.status()).toBe(201)
  await page.reload()
  await page.getByRole('button', { name: new RegExp(name) }).click()
  await page.getByRole('button', { name: '刪除比賽', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '確認刪除比賽？' })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText(name)
  await expect(dialog).toContainText('正取 1 人')
  await expect(dialog.getByRole('button', { name: '保留比賽' })).toBeFocused()
  expect(await dialog.evaluate(el => { const r = el.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && r.top >= 0 && r.bottom <= innerHeight })).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('delete-confirmation.png') })
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: '刪除比賽', exact: true }).click()
  await dialog.getByRole('button', { name: '保留比賽' }).click()
  await expect(page.locator('.roster-confirmed tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: '刪除比賽', exact: true }).click()
  await dialog.getByRole('button', { name: '確認刪除', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('比賽已刪除')
  await expect(page.locator('.competition-items')).not.toContainText(name)
  const schedule = await (await page.request.get('/api/public/schedule')).json()
  expect(schedule.some((c: { id: string }) => c.id === competition.id)).toBe(false)
  await page.getByRole('button', { name: '已刪除', exact: true }).click()
  await page.getByRole('button', { name: new RegExp(name) }).click()
  await expect(page.getByLabel('名稱', { exact: true })).toBeDisabled()
  await expect(page.locator('.roster-confirmed tbody tr')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '取消', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '還原比賽', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('重新開放報名')
  await page.getByRole('button', { name: '確認還原', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('比賽已還原')
  await page.getByRole('button', { name: '目前比賽', exact: true }).click()
  await page.getByRole('button', { name: new RegExp(name) }).click()
  await expect(page.getByLabel('名稱', { exact: true })).toBeEnabled()
  await expect(page.locator('.roster-confirmed tbody tr')).toHaveCount(1)
  await expect(page.locator('.summary-grid')).toContainText('0/1/0')
  await page.screenshot({ path: testInfo.outputPath('restored-roster.png') })
})
