import { expect, test } from '@playwright/test'

const prefix=(process.env.FUCHENG_BASE_PATH??'').replace(/\/$/,'')
const url=(path:string)=>prefix+path

test('每場可刪除空級數欄、加回、保存與列印；有人的欄保持保護',async({page},info)=>{
  await page.goto(url('/admin/competitions'))
  await page.getByLabel('帳號',{exact:true}).fill('e2e-admin')
  await page.getByLabel('密碼',{exact:true}).fill(process.env.FUCHENG_E2E_ADMIN_PASSWORD!)
  await page.getByRole('button',{name:'登入',exact:true}).click()
  await expect(page.getByRole('button',{name:'登出',exact:true})).toBeVisible()
  const auth=await (await page.request.get(url('/api/auth/me'))).json(),headers={'X-CSRF-Token':auth.csrf_token}
  const compResponse=await page.request.post(url('/api/admin/competitions'),{headers,data:{name:`合成自由級數-${info.project.name}`,competition_date:'2099-10-10',registration_deadline:'2099-10-09T00:00:00+08:00',capacity:10,status:'open',notes:'合成測試'}})
  expect(compResponse.status()).toBe(201);const comp=await compResponse.json()
  const members=await (await page.request.get(url('/api/admin/members'))).json()
  const member=members.find((m:any)=>m.name==='合成會員一')
  const registered=await page.request.post(url(`/api/admin/competitions/${comp.id}/registrations`),{headers,data:{member_id:member.id,request_id:crypto.randomUUID()}})
  expect(registered.status()).toBe(201)
  await page.reload();await page.getByLabel('選擇比賽',{exact:true}).selectOption(comp.id)
  const area=page.getByRole('region',{name:'當次比賽級數安排'}),cols=area.locator('col[data-column-id]')
  await expect(cols).toHaveCount(10)
  const endpoint=url(`/api/admin/competitions/${comp.id}/arrangement`)
  const state=async()=>await (await page.request.get(endpoint)).json()
  const initial=await state()
  await area.getByRole('button',{name:'第 1 直欄更多操作',exact:true}).click()
  await expect(page.getByRole('button',{name:'刪除這個級數欄',exact:true})).toBeDisabled()
  await page.getByRole('button',{name:'關閉',exact:true}).click()
  await area.getByRole('button',{name:'第 2 直欄更多操作',exact:true}).click()
  await page.getByRole('button',{name:'刪除這個級數欄',exact:true}).click()
  await expect(cols).toHaveCount(9)
  await expect(area.getByLabel('加回級數欄',{exact:true})).toBeEnabled()
  expect((await state()).rows).toEqual(initial.rows)
  const afterDelete=await state()
  await area.getByLabel('加回級數欄',{exact:true}).selectOption('2')
  await expect(cols).toHaveCount(10)
  await expect(area.getByLabel('加回級數欄',{exact:true})).toHaveCount(0)
  expect((await state()).layout.columns.at(-1).level).toBe(2)
  await area.getByRole('button',{name:'第 10 直欄更多操作',exact:true}).click()
  await page.getByRole('button',{name:'刪除這個級數欄',exact:true}).click()
  await expect(cols).toHaveCount(9)
  await area.getByRole('button',{name:'保存完整安排',exact:true}).click()
  const save=page.getByRole('dialog',{name:'保存完整安排'})
  await save.getByLabel('版本名稱',{exact:true}).fill('九欄版')
  await save.getByRole('button',{name:'保存',exact:true}).click()
  await expect.poll(async()=>(await state()).latest?.label).toBe('九欄版')
  await page.reload();await expect(cols).toHaveCount(9)
  expect((await state()).layout.columns.map((c:any)=>c.id)).toEqual(afterDelete.layout.columns.map((c:any)=>c.id))
  await area.getByRole('button',{name:'歷史',exact:true}).click()
  await page.locator('.version-item').filter({hasText:'九欄版'}).click()
  await expect(area.getByRole('button',{name:'回目前安排',exact:true})).toBeVisible()
  await expect(area.getByLabel('加回級數欄',{exact:true})).toHaveCount(0)
  await expect(cols).toHaveCount(9)
  await page.evaluate(()=>window.print=()=>{})
  await area.getByRole('button',{name:'列印安排',exact:true}).click()
  await expect(page.locator('[data-print-header]')).toHaveCount(9)
  await expect(page.locator('[data-print-registration]')).toHaveCount(1)
  if(info.project.name==='desktop')await page.pdf({path:info.outputPath('nine-columns.pdf'),preferCSSPageSize:true})
  await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')))
  const pending=page.waitForEvent('download');await area.getByRole('button',{name:'匯出 Excel',exact:true}).click();const download=await pending
  expect(await download.failure()).toBeNull();await download.saveAs(info.outputPath('nine-columns.xlsx'))
  await area.getByRole('button',{name:'回目前安排',exact:true}).click()
  await expect(area.getByLabel('加回級數欄',{exact:true})).toBeVisible()
  await page.screenshot({path:info.outputPath('flexible-level-columns.png'),fullPage:true})
})
