import { expect, test, type Page, type TestInfo } from '@playwright/test'

const prefix = (process.env.FUCHENG_BASE_PATH ?? '').replace(/\/$/, '')
const url = (path: string) => prefix + path
const activate = (info: TestInfo, locator: any) => info.project.name === 'mobile' ? locator.tap() : locator.click()

async function setup(page: Page, info: TestInfo) {
  await page.goto(url('/admin/competitions'))
  await page.getByLabel('帳號', { exact: true }).fill('e2e-admin')
  await page.getByLabel('密碼', { exact: true }).fill(process.env.FUCHENG_E2E_ADMIN_PASSWORD!)
  await page.getByRole('button', { name: '登入', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '管理功能' })).toBeVisible()
  const me = await (await page.request.get(url('/api/auth/me'))).json(), headers = { 'X-CSRF-Token': me.csrf_token }
  const comp = await (await page.request.post(url('/api/admin/competitions'), { headers, data: { name: `手機流程-${info.project.name}-${info.testId}`, competition_date: '2099-09-20', registration_deadline: '2099-09-19T00:00:00+08:00', capacity: 10, status: 'open', notes: '僅合成資料' } })).json()
  const people: any[] = []
  for (let i = 0; i < 3; i++) {
    const member = await (await page.request.post(url('/api/admin/members'), { headers, data: { name: i < 2 ? '合成同名操作' : '合成操作三', distinguishing_note: `辨識${i}`, level: i + 1, diet: i === 0 ? 'vegetarian' : 'unset', is_active: true } })).json()
    const registration = await page.request.post(url(`/api/admin/competitions/${comp.id}/registrations`), { headers, data: { member_id: member.id, request_id: crypto.randomUUID() } })
    expect(registration.status()).toBe(201); people.push(await registration.json())
  }
  await page.reload()
  await page.getByLabel('選擇比賽', { exact: true }).selectOption(comp.id)
  const area = page.getByRole('region', { name: '當次比賽級數安排' })
  const endpoint = url(`/api/admin/competitions/${comp.id}/arrangement`)
  const state = async () => (await page.request.get(endpoint)).json()
  await expect.poll(async () => !!(await state()).layout).toBe(true)
  await expect(area.locator('.arrangement-status')).not.toContainText('讀取中')
  return { area, endpoint, state, people, headers, comp }
}
const position = (state: any, id: string) => { const cell = state.layout.cells.find((c: any) => c.registration_id === id); return [cell.row_id, cell.column_id] }

async function openPlayer(page: Page, info: TestInfo, note = '辨識0') {
  await activate(info, page.getByRole('button', { name: new RegExp(`^操作 .*${note}`) }))
  const dialog = page.getByRole('dialog', { name: /安排操作/ })
  await expect(dialog).toBeVisible()
  return dialog
}

test('點選交換、插入、空格與欄底共用保存復原，切換尺寸保留操作', async ({ page }, info) => {
  const s = await setup(page, info)
  await expect(s.area.getByRole('button', { name: info.project.name === 'mobile' ? '名單操作' : '完整表格', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await activate(info, s.area.getByRole('button', { name: '名單操作', exact: true }))
  const before = await s.state()
  let dialog = await openPlayer(page, info)
  await dialog.getByLabel('調整方式').selectOption('swap')
  await dialog.getByLabel('目標選手').selectOption(s.people[1].id)
  await expect(dialog.getByLabel('調整預覽')).toContainText('辨識1')
  await page.screenshot({ path: info.outputPath('operation-preview.png'), fullPage: true })
  await page.setViewportSize({ width: 768, height: 900 })
  await expect(dialog.getByLabel('目標選手')).toHaveValue(s.people[1].id)
  await activate(info, dialog.getByRole('button', { name: '確認調整' }))
  await expect(dialog).toHaveCount(0)
  let after = await s.state()
  expect(position(after, s.people[0].id)).toEqual(position(before, s.people[1].id))
  expect(position(after, s.people[1].id)).toEqual(position(before, s.people[0].id))
  await activate(info, s.area.getByRole('group', { name: '名單復原' }).getByRole('button', { name: '復原上一個動作' }))
  await expect.poll(async () => position(await s.state(), s.people[0].id)).toEqual(position(before, s.people[0].id))
  await expect(s.area.getByRole('group', { name: '名單復原' }).getByRole('button', { name: '重做', exact: true })).toBeEnabled()
  await activate(info, s.area.getByRole('group', { name: '名單復原' }).getByRole('button', { name: '重做', exact: true }))
  await expect.poll(async () => position(await s.state(), s.people[0].id)).toEqual(position(before, s.people[1].id))
  dialog = await openPlayer(page, info)
  await dialog.getByLabel('調整方式').selectOption('insert')
  await dialog.getByLabel('目標選手').selectOption(s.people[2].id)
  await dialog.getByLabel('插入位置').selectOption('before')
  await activate(info, dialog.getByRole('button', { name: '確認調整' })); await expect(dialog).toHaveCount(0)
  after = await s.state(); expect(after.rows.find((r: any) => r.registration_id === s.people[0].id).competition_level).toBe(3)
  dialog = await openPlayer(page, info)
  await dialog.getByLabel('調整方式').selectOption('move_empty')
  await dialog.getByLabel('目標級數').selectOption('4')
  const empty = await dialog.getByLabel('目標空格').locator('option').nth(1).getAttribute('value')
  await dialog.getByLabel('目標空格').selectOption(empty!)
  await activate(info, dialog.getByRole('button', { name: '確認調整' })); await expect(dialog).toHaveCount(0)
  expect(position(await s.state(), s.people[0].id).join('/')).toBe(empty)
  dialog = await openPlayer(page, info)
  await dialog.getByLabel('目標級數').selectOption('5')
  await activate(info, dialog.getByRole('button', { name: '確認調整' })); await expect(dialog).toHaveCount(0)
  expect((await s.state()).rows.find((r: any) => r.registration_id === s.people[0].id).competition_level).toBe(5)
  for (const width of [360, 390, 430, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath(`arrangement-${width}.png`), fullPage: true })
  }
  await activate(info, s.area.getByRole('button', { name: '完整表格', exact: true }))
  await expect(s.area.getByRole('table', { name: '當次級數表' })).toBeVisible()
  const beforeSwitch = await s.state()
  await s.area.locator('.grid-column-title').first().dblclick()
  await page.getByLabel('直接編輯文字').fill('未提交表頭草稿')
  await activate(info, s.area.getByRole('button', { name: '名單操作', exact: true }))
  await expect(s.area.getByRole('button', { name: '名單操作', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await activate(info, s.area.getByRole('button', { name: '完整表格', exact: true }))
  await expect(page.getByLabel('直接編輯文字')).toHaveValue('未提交表頭草稿')
  expect((await s.state()).state_token).toBe(beforeSwitch.state_token)
  await page.getByLabel('直接編輯文字').press('Escape')
  await activate(info, s.area.getByRole('button', { name: '保存完整安排', exact: true }))
  const save = page.getByRole('dialog', { name: '保存完整安排' })
  await save.getByLabel('版本名稱').fill('手機完成版')
  await activate(info, save.getByRole('button', { name: '保存', exact: true }))
  await expect(s.area.locator('.arrangement-status')).toContainText('已保存「手機完成版」')
  const saved = await s.state()
  expect(saved.latest.rows).toEqual(saved.rows)
  await activate(info, s.area.getByRole('button', { name: '名單操作', exact: true }))
  await activate(info, s.area.getByRole('button', { name: '歷史', exact: true }))
  await expect(s.area.getByRole('heading', { name: '版本紀錄', exact: true })).toBeVisible()
  await activate(info, s.area.locator('.version-item').filter({ hasText: '手機完成版' }))
  await activate(info, s.area.getByRole('button', { name: '名單操作', exact: true }))
  dialog = await openPlayer(page, info)
  await expect(dialog.getByText('此版本唯讀，可返回完整表格檢視。')).toBeVisible()
  await expect(dialog.getByRole('button', { name: '確認調整' })).toHaveCount(0)
})

test('送出後連線中斷保留原請求，手機無法重複調整並可安全恢復', async ({ page }, info) => {
  const s = await setup(page, info)
  await activate(info, s.area.getByRole('button', { name: '名單操作', exact: true }))
  const writes: any[] = []
  let first = true
  await page.route('**/arrangement/operations', async route => {
    writes.push(route.request().postDataJSON())
    if (first) { first = false; await route.fetch(); await route.abort('failed') }
    else await route.continue()
  })
  const dialog = await openPlayer(page, info)
  await dialog.getByLabel('目標級數').selectOption('7')
  await activate(info, dialog.getByRole('button', { name: '確認調整' }))
  await expect(dialog.getByRole('button', { name: '確認調整' })).toBeDisabled()
  await activate(info, dialog.getByRole('button', { name: '返回名單' }))
  await expect(s.area.getByRole('button', { name: /操作 .*辨識0/ })).toBeDisabled()
  await expect(s.area.locator('.arrangement-recovery')).toContainText('結果尚未確認')
  await activate(info, s.area.getByRole('button', { name: '確認操作結果／原樣重試' }))
  await expect(s.area.locator('.arrangement-recovery')).toHaveCount(0)
  const result = await s.state()
  expect(result.rows.find((r: any) => r.registration_id === s.people[0].id).competition_level).toBe(7)
  expect(writes).toHaveLength(2); expect(writes[1]).toEqual(writes[0])
})

test('手機會員與公告分頁保留草稿，報名操作使用可關閉的觸控面板', async ({ page }, info) => {
  const s = await setup(page, info)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('link', { name: '會員管理', exact: true }).click()
  await page.getByLabel('搜尋會員').fill('合成會員一')
  await page.getByRole('button', { name: /合成會員一/ }).click()
  await page.getByLabel('重名辨識註記').fill('保留中的手機草稿')
  await page.getByRole('button', { name: '← 返回會員清單（保留輸入）' }).click()
  await expect(page.getByLabel('姓名（必填）')).toBeHidden()
  await page.getByRole('button', { name: /合成會員一/ }).click()
  await expect(page.getByLabel('重名辨識註記')).toHaveValue('保留中的手機草稿')
  await page.setViewportSize({ width: 1440, height: 900 }); await expect(page.getByLabel('搜尋會員')).toBeVisible()
  await expect(page.getByLabel('重名辨識註記')).toHaveValue('保留中的手機草稿')
  await page.setViewportSize({ width: 390, height: 844 }); await expect(page.getByLabel('重名辨識註記')).toHaveValue('保留中的手機草稿')
  await page.getByRole('link', { name: '公告管理', exact: true }).click()
  await page.getByRole('button', { name: '新增公告' }).click()
  await page.getByLabel('公告標題').fill('合成手機公告')
  await page.getByLabel('公告內容').fill('公告草稿')
  await page.getByRole('button', { name: '← 返回公告清單（保留輸入）' }).click()
  await page.getByRole('button', { name: '繼續編輯公告' }).click()
  await expect(page.getByLabel('公告內容')).toHaveText('公告草稿')
  await page.setViewportSize({ width: 1440, height: 900 }); await expect(page.getByLabel('公告內容')).toHaveText('公告草稿')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('link', { name: '比賽管理', exact: true }).click()
  await page.getByLabel('選擇比賽', { exact: true }).selectOption(s.comp.id)
  await page.getByRole('button', { name: '報名與設定', exact: true }).click()
  await page.locator('.mobile-registration-list').getByRole('button', { name: /合成同名操作/ }).first().click()
  const panel = page.getByRole('dialog', { name: '報名管理操作' })
  await expect(panel).toBeVisible()
  await expect(panel.getByLabel('合成同名操作當次餐食')).toBeVisible()
  await page.screenshot({ path: info.outputPath('registration-sheet.png'), fullPage: true })
  await page.keyboard.press('Escape'); await expect(panel).toHaveCount(0)
})

test('外來更新使手機舊操作遭拒，重新核對後不自動套用或覆寫', async ({ page }, info) => {
  const s = await setup(page, info)
  await activate(info, s.area.getByRole('button', { name: '名單操作', exact: true }))
  const dialog = await openPlayer(page, info)
  await dialog.getByLabel('調整方式').selectOption('swap')
  await dialog.getByLabel('目標選手').selectOption(s.people[1].id)
  const before = await s.state()
  const external = await page.request.post(s.endpoint + '/operations', { headers: s.headers, data: { request_id: crypto.randomUUID(), state_token: before.state_token, operation: { action: 'move_bottom', registration_id: s.people[0].id, level: 8 } } })
  expect(external.status()).toBe(200)
  const writes: any[] = []
  page.on('request', request => { if (request.url().endsWith('/arrangement/operations')) writes.push(request.postDataJSON()) })
  await activate(info, dialog.getByRole('button', { name: '確認調整' }))
  await expect(dialog.getByRole('button', { name: '確認調整' })).toBeDisabled()
  await activate(info, dialog.getByRole('button', { name: '返回名單' }))
  await activate(info, s.area.getByRole('button', { name: '重新讀取並核對', exact: true }))
  await expect(s.area.locator('.arrangement-recovery')).toHaveCount(0)
  expect(writes).toHaveLength(1)
  expect(writes[0].state_token).toBe(before.state_token)
  const after = await s.state()
  expect(after.rows.find((r: any) => r.registration_id === s.people[0].id).competition_level).toBe(8)
  expect(after.rows.find((r: any) => r.registration_id === s.people[1].id).competition_level).toBe(2)
})
