import { expect, test } from '@playwright/test'

test('免登入搜尋同名會員、選餐食報名、管理員取消及重新排尾', async ({ page, browser }, testInfo) => {
  const suffix=testInfo.project.name
  const name=`合成免登入賽-${suffix}`
  await page.goto('/admin')
  await page.getByLabel('帳號', { exact:true }).fill('e2e-admin')
  await page.getByLabel('密碼', { exact:true }).fill(process.env.FUCHENG_E2E_ADMIN_PASSWORD!)
  await page.getByRole('button',{name:'登入',exact:true}).click()
  await page.getByRole('link',{name:'比賽管理'}).click()
  await page.getByRole('button',{name:'報名與設定',exact:true}).click()
  await page.getByRole('button',{name:'建立比賽'}).click()
  await page.getByLabel('名稱',{exact:true}).fill(name)
  await page.getByLabel('比賽日期').fill(new Date(Date.now()+7*86400000).toISOString().slice(0,10))
  await page.getByLabel('名額上限').fill('1')
  await page.getByLabel('報名截止時間（台北時間）').fill(new Date(Date.now()+5*86400000).toISOString().slice(0,16))
  await page.getByRole('combobox',{name:'狀態',exact:true}).selectOption('open')
  await page.getByLabel('備註',{exact:true}).fill('免登入報名合成測試')
  await page.getByRole('button',{name:'儲存比賽'}).click()
  await expect(page.getByText('比賽已建立',{exact:true})).toBeVisible()
  for (const member of ['合成會員一','合成會員二']) {
    const picker=page.locator('.candidate-picker')
    if (!(await picker.evaluate(el=>(el as HTMLDetailsElement).open))) await picker.locator('summary').click()
    await page.getByLabel('搜尋姓名／辨識註記',{exact:true}).fill(member)
    await page.getByRole('button',{name:new RegExp(member)}).click()
    await expect(page.locator('.roster-section').getByText(member,{exact:true})).toBeVisible()
  }
  const context=await browser.newContext({viewport:testInfo.project.use.viewport,isMobile:testInfo.project.use.isMobile})
  const visitor=await context.newPage()
  await visitor.goto('/competitions')
  await expect(visitor.getByRole('heading',{name:'比賽報名',exact:true})).toBeVisible()
  await expect(visitor.locator('input[type=password]')).toHaveCount(0)
  await visitor.getByRole('link',{name:`我要報名：${name}`,exact:true}).click()
  await visitor.getByLabel('搜尋姓名',{exact:true}).fill('合成同名')
  await expect(visitor.locator('.public-candidates button')).toHaveCount(2)
  await visitor.getByRole('button',{name:'合成同名 西區',exact:true}).click()
  await expect(visitor.getByRole('radio')).toHaveCount(2)
  await expect(visitor.getByRole('radio',{name:'葷食',exact:true})).toBeChecked()
  await visitor.getByRole('radio',{name:'素食',exact:true}).check()
  await expect(visitor.locator('.registration-confirm')).toContainText('合成同名（西區）')
  expect(await visitor.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await visitor.screenshot({path:testInfo.outputPath('public-confirm.png'),fullPage:true})
  await visitor.route('**/api/public/competitions/*/registrations',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'合成連線失敗'})}))
  await visitor.getByRole('button',{name:'確認以 合成同名 報名',exact:true}).click()
  await expect(visitor.getByRole('alert')).toContainText('姓名與餐食已保留')
  await expect(visitor.getByRole('radio',{name:'素食',exact:true})).toBeChecked()
  await visitor.unroute('**/api/public/competitions/*/registrations')
  await visitor.getByRole('button',{name:'確認以 合成同名 報名',exact:true}).click()
  await expect(visitor.getByRole('status')).toHaveText('報名完成')
  await expect(visitor.locator('.registration-receipt')).toContainText('合成同名（西區）')
  await expect(visitor.locator('.receipt-status')).toHaveText('候補')
  await expect(visitor.getByRole('button',{name:/取消/})).toHaveCount(0)
  expect(await visitor.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await visitor.screenshot({path:testInfo.outputPath('public-receipt.png'),fullPage:true})
  await page.reload()
  await page.getByRole('button',{name:'報名與設定',exact:true}).click()
  await page.getByRole('button',{name:new RegExp(name)}).click()
  const row=page.locator('.roster-waitlisted').getByRole('row').filter({hasText:'合成同名'})
  await expect(row).toContainText('西區')
  await expect(row).toContainText('免登入報名（身分未驗證）')
  await expect(row.getByRole('cell').first()).toHaveText('3')
  await row.getByRole('button',{name:'取消',exact:true}).click()
  await expect(page.locator('.roster-cancelled')).toContainText('合成同名')
  await visitor.getByRole('link',{name:'回比賽清單',exact:true}).click()
  await visitor.getByRole('link',{name:`我要報名：${name}`,exact:true}).click()
  await visitor.getByLabel('搜尋姓名',{exact:true}).fill('合成同名')
  await visitor.getByRole('button',{name:'合成同名 西區',exact:true}).click()
  await visitor.getByRole('radio',{name:'素食',exact:true}).check()
  await visitor.getByRole('button',{name:'確認以 合成同名 報名',exact:true}).click()
  await expect(visitor.getByRole('status')).toHaveText('報名完成')
  await page.reload()
  await page.getByRole('button',{name:'報名與設定',exact:true}).click()
  await page.getByRole('button',{name:new RegExp(name)}).click()
  await expect(page.locator('.roster-waitlisted').getByRole('row').filter({hasText:'合成同名'}).getByRole('cell').first()).toHaveText('4')
  await page.getByText('報名操作稽核',{exact:true}).click()
  await expect(page.locator('.registration-history li').filter({hasText:'免登入報名'})).toHaveCount(2)
  await expect(page.locator('.registration-history li').filter({hasText:'管理員：e2e-admin・取消報名'})).toHaveCount(1)
  await page.screenshot({path:testInfo.outputPath('public-admin-audit.png'),fullPage:true})
  await context.close()
})
