import { expect, test } from '@playwright/test'

test('免登入搜尋同名會員、選餐食報名、管理員取消及重新排尾', async ({ page, browser }, testInfo) => {
  const suffix=testInfo.project.name
  const name=`合成免登入賽-${suffix}`
  await page.goto('/admin')
  await page.getByLabel('帳號', { exact:true }).fill('e2e-admin')
  await page.getByLabel('密碼', { exact:true }).fill(process.env.FUCHENG_E2E_ADMIN_PASSWORD!)
  await page.getByRole('button',{name:'登入',exact:true}).click()
  await page.getByRole('link',{name:'比賽管理'}).click()
  await page.getByRole('button',{name:'報名與設定',exact:true}).click()
  await page.getByRole('button',{name:'建立比賽'}).click()
  await page.getByLabel('名稱',{exact:true}).fill(name)
  await page.getByLabel('比賽日期').fill(new Date(Date.now()+7*86400000).toISOString().slice(0,10))
  await page.getByLabel('名額上限').fill('1')
  await page.getByLabel('報名截止時間（台北時間）').fill(new Date(Date.now()+5*86400000).toISOString().slice(0,16))
  await page.getByRole('combobox',{name:'狀態',exact:true}).selectOption('open')
  await page.getByLabel('備註',{exact:true}).fill('免登入報名合成測試')
  await page.getByRole('button',{name:'儲存比賽'}).click()
  await expect(page.getByText('比賽已建立',{exact:true})).toBeVisible()
  for (const member of ['合成會員一','合成會員二']) {
    const picker=page.locator('.candidate-picker')
    if (!(await picker.evaluate(el=>(el as HTMLDetailsElement).open))) await picker.locator('summary').click()
    await page.getByLabel('搜尋姓名／辨識註記',{exact:true}).fill(member)
    await page.getByRole('button',{name:new RegExp(member)}).click()
    if (member === '合成會員一') await expect(page.getByRole('region',{name:'十級行政名單'}).getByRole('button',{name:/合成會員一，正取/})).toBeVisible()
    else await expect(page.getByRole('button',{name:/候補 1 人 展開/})).toBeVisible()
  }
  const context=await browser.newContext({viewport:testInfo.project.use.viewport,isMobile:testInfo.project.use.isMobile})
  const visitor=await context.newPage()
  await visitor.goto('/competitions')
  await expect(visitor.getByRole('heading',{name:'比賽報名',exact:true})).toBeVisible()
  await expect(visitor.locator('input[type=password]')).toHaveCount(0)
  await visitor.getByRole('link',{name:`我要報名：${name}`,exact:true}).click()
  await visitor.getByLabel('搜尋姓名',{exact:true}).fill('合成同名')
  await expect(visitor.locator('.public-candidates button')).toHaveCount(2)
  await visitor.getByRole('button',{name:'合成同名 西區',exact:true}).click()
  await expect(visitor.getByRole('radio')).toHaveCount(2)
  await expect(visitor.getByRole('radio',{name:'葷食',exact:true})).toBeChecked()
  await visitor.getByRole('radio',{name:'素食',exact:true}).check()
  await expect(visitor.locator('.registration-confirm')).toContainText('合成同名（西區）')
  expect(await visitor.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await visitor.screenshot({path:testInfo.outputPath('public-confirm.png'),fullPage:true})
  const failedKeys: string[] = []
  await visitor.route('**/api/public/competitions/*/registrations',route=>{
    failedKeys.push(route.request().postDataJSON().request_id)
    return route.fulfill({status:403,contentType:'text/html',body:'<html><body>synthetic edge challenge</body></html>'})
  })
  await visitor.getByRole('button',{name:'確認以 合成同名 報名',exact:true}).click()
  await expect(visitor.getByRole('alert')).toContainText('安全檢查或連線暫時無法完成')
  await expect(visitor.getByLabel('搜尋姓名',{exact:true})).toHaveValue('合成同名')
  await expect(visitor.getByRole('radio',{name:'素食',exact:true})).toBeChecked()
  await visitor.unroute('**/api/public/competitions/*/registrations')
  await visitor.route('**/api/public/competitions/*/registrations',route=>{
    failedKeys.push(route.request().postDataJSON().request_id)
    return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'合成連線失敗'})})
  })
  await visitor.getByRole('button',{name:'確認以 合成同名 報名',exact:true}).click()
  await expect(visitor.getByRole('alert')).toContainText('姓名與餐食已保留')
  await expect(visitor.getByRole('radio',{name:'素食',exact:true})).toBeChecked()
  expect(failedKeys).toHaveLength(2)
  expect(failedKeys[1]).toBe(failedKeys[0])
  await visitor.unroute('**/api/public/competitions/*/registrations')
  await visitor.getByRole('button',{name:'確認以 合成同名 報名',exact:true}).click()
  await expect(visitor.getByRole('status')).toHaveText('報名完成')
  await expect(visitor.locator('.registration-receipt')).toContainText('合成同名（西區）')
  await expect(visitor.locator('.receipt-status')).toHaveText('候補')
  await expect(visitor.getByRole('button',{name:/取消/})).toHaveCount(0)
  expect(await visitor.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await visitor.screenshot({path:testInfo.outputPath('public-receipt.png'),fullPage:true})

  // Synthetic Siteverify timeout UI: the widget script and session sitekey are
  // stubbed locally; no real Cloudflare domain or credentials are contacted.
  const challengeContext=await browser.newContext({viewport:testInfo.project.use.viewport,isMobile:testInfo.project.use.isMobile})
  const challenge=await challengeContext.newPage()
  await challenge.route('**/api/public/registration-session',async route=>{
    const response=await route.fetch()
    await route.fulfill({response,json:{...await response.json(),turnstile_sitekey:'synthetic-sitekey'}})
  })
  await challenge.route('https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit',route=>route.fulfill({
    status:200,contentType:'application/javascript',body:`window.turnstile={
      render:function(_element,options){window.__turnstileOptions=options;setTimeout(function(){options.callback('synthetic-token')},0);return 'synthetic-widget'},
      reset:function(){window.__turnstileResets=(window.__turnstileResets||0)+1},remove:function(){}};`,
  }))
  await challenge.goto(`/register/${await page.getByRole('combobox',{name:'選擇比賽'}).inputValue()}`)
  await challenge.getByLabel('搜尋姓名',{exact:true}).fill('合成同名')
  await expect(challenge.locator('.public-candidates button')).toHaveCount(2)
  await challenge.getByRole('button',{name:'合成同名 東區',exact:true}).click()
  await challenge.getByRole('radio',{name:'素食',exact:true}).check()
  await challenge.waitForFunction(()=>Boolean((window as any).__turnstileOptions))
  expect(await challenge.evaluate(()=>(window as any).__turnstileOptions.appearance)).toBe('interaction-only')
  const timeoutKeys: string[]=[]
  await challenge.route('**/api/public/competitions/*/registrations',route=>{
    const body=route.request().postDataJSON()
    timeoutKeys.push(body.request_id)
    expect(body.turnstile_token).toMatch(/^synthetic-token/)
    return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'安全驗證暫時無法連線，請稍後再試'})})
  })
  await challenge.getByRole('button',{name:'確認以 合成同名 報名',exact:true}).click()
  await expect(challenge.getByRole('alert')).toContainText('安全驗證暫時無法連線')
  await expect(challenge.getByLabel('搜尋姓名',{exact:true})).toHaveValue('合成同名')
  await expect(challenge.getByRole('radio',{name:'素食',exact:true})).toBeChecked()
  await expect.poll(()=>challenge.evaluate(()=>(window as any).__turnstileResets)).toBe(1)
  await challenge.evaluate(()=>(window as any).__turnstileOptions.callback('synthetic-token-new'))
  await challenge.getByRole('button',{name:'確認以 合成同名 報名',exact:true}).click()
  await expect.poll(()=>timeoutKeys.length).toBe(2)
  expect(timeoutKeys[1]).toBe(timeoutKeys[0])
  await challengeContext.close()
  await page.reload()
  await page.getByRole('button',{name:'報名與設定',exact:true}).click()
  await page.getByRole('button',{name:new RegExp(name)}).click()
  await page.getByRole('button',{name:/候補 2 人 展開/}).click()
  const waiting=page.getByRole('region',{name:'十級行政名單'}).getByRole('button',{name:/合成同名，候補，3 號/})
  await expect(waiting).toBeVisible()
  await waiting.click()
  await expect(page.getByRole('region',{name:'報名管理操作'})).toContainText('西區')
  await page.getByRole('button',{name:'取消報名',exact:true}).click()
  await expect(page.getByRole('button',{name:/已取消 1 人 展開/})).toBeVisible()
  await visitor.getByRole('link',{name:'回比賽清單',exact:true}).click()
  await visitor.getByRole('link',{name:`我要報名：${name}`,exact:true}).click()
  await visitor.getByLabel('搜尋姓名',{exact:true}).fill('合成同名')
  await visitor.getByRole('button',{name:'合成同名 西區',exact:true}).click()
  await visitor.getByRole('radio',{name:'素食',exact:true}).check()
  await visitor.getByRole('button',{name:'確認以 合成同名 報名',exact:true}).click()
  await expect(visitor.getByRole('status')).toHaveText('報名完成')
  await page.reload()
  await page.getByRole('button',{name:'報名與設定',exact:true}).click()
  await page.getByRole('button',{name:new RegExp(name)}).click()
  await page.getByRole('button',{name:/候補 2 人 展開/}).click()
  await expect(page.getByRole('region',{name:'十級行政名單'}).getByRole('button',{name:/合成同名，候補，4 號/})).toBeVisible()
  const competitionId = await page.getByRole('combobox',{name:'選擇比賽'}).inputValue()
  const historyResponse = await page.request.get(`/api/admin/competitions/${competitionId}/history`)
  expect(historyResponse.ok()).toBe(true)
  const history = await historyResponse.json() as Array<{actor_kind:string; action:string}>
  expect(history.filter(entry => entry.actor_kind === 'public' && entry.action === 'create')).toHaveLength(2)
  expect(history.filter(entry => entry.actor_kind === 'admin' && entry.action === 'cancel')).toHaveLength(1)
  await page.screenshot({path:testInfo.outputPath('public-admin-audit.png'),fullPage:true})
  await context.close()
})
