import { expect, test } from '@playwright/test'

test('首頁公告發布下架、免登入分級與比賽導覽', async ({ page, browser }, testInfo) => {
  const title = `合成球館公告-${testInfo.project.name}`
  await page.goto('/admin')
  await page.getByLabel('帳號', { exact: true }).fill('e2e-admin')
  await page.getByLabel('密碼', { exact: true }).fill(process.env.FUCHENG_E2E_ADMIN_PASSWORD!)
  await page.getByRole('button', { name: '登入', exact: true }).click()
  await page.getByRole('link', { name: '公告管理', exact: true }).click()
  await page.getByRole('button', { name: '新增公告', exact: true }).click()
  await page.getByLabel('公告標題').fill(title)
  await page.getByLabel('公告內容').fill('合成公告第一行\n合成公告第二行 <script>window.unsafe=true</script>')
  await page.getByRole('button', { name: '儲存公告', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('公告已儲存')
  const context = await browser.newContext({ viewport: testInfo.project.use.viewport, isMobile: testInfo.project.use.isMobile })
  const visitor = await context.newPage()
  await visitor.goto('/')
  await expect(visitor.getByRole('heading', { name: '最新公告', exact: true })).toBeVisible()
  await expect(visitor.getByRole('heading', { name: title, exact: true })).toHaveCount(0)
  await page.getByLabel('發布到首頁').check()
  await page.getByLabel('置頂公告').check()
  await page.getByRole('button', { name: '儲存公告', exact: true }).click()
  await expect(page.getByLabel('發布到首頁')).toBeChecked()
  await expect(page.getByRole('button', { name: `${title} 已發布・置頂`, exact: true })).toBeVisible()
  await visitor.reload()
  await expect(visitor.getByRole('heading', { name: title, exact: true })).toBeVisible()
  await expect(visitor.locator('.news-card').filter({ hasText: title })).toContainText('<script>window.unsafe=true</script>')
  expect(await visitor.evaluate(() => 'unsafe' in window)).toBe(false)
  expect(await visitor.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await visitor.screenshot({ path: testInfo.outputPath('club-home.png'), fullPage: true })
  await visitor.getByRole('navigation').getByRole('link', { name: '會員分級', exact: true }).click()
  await expect(visitor.getByRole('heading', { name: '會員硬實力分級', exact: true })).toBeVisible()
  await visitor.getByLabel('搜尋姓名或辨識註記').fill('合成同名')
  await expect(visitor.locator('.level-card tbody tr')).toHaveCount(2)
  await visitor.getByRole('combobox', { name: /級數/ }).selectOption('8')
  await expect(visitor.locator('.level-card tbody tr')).toHaveCount(1)
  await expect(visitor.locator('.level-card')).toContainText('西區')
  await expect(visitor.locator('input[type=password]')).toHaveCount(0)
  await visitor.getByRole('navigation').getByRole('link', { name: '比賽報名', exact: true }).click()
  await expect(visitor.getByRole('heading', { name: '比賽報名', exact: true })).toBeVisible()
  await visitor.getByRole('navigation').getByRole('link', { name: '最新消息', exact: true }).click()
  await expect(visitor.getByRole('heading', { name: '比賽時程', exact: true })).toBeVisible()
  await page.route('**/api/admin/announcements/*', route => route.request().method() === 'PUT' ? route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ detail: '合成版本衝突' }) }) : route.continue())
  await page.getByLabel('公告內容').fill('合成衝突時保留內容')
  await page.getByRole('button', { name: '儲存公告', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('合成版本衝突')
  await expect(page.getByLabel('公告內容')).toHaveValue('合成衝突時保留內容')
  await page.unroute('**/api/admin/announcements/*')
  await page.getByLabel('發布到首頁').uncheck()
  await page.getByRole('button', { name: '儲存公告', exact: true }).click()
  await expect(page.getByRole('button', { name: `${title} 未發布・置頂`, exact: true })).toBeVisible()
  await visitor.reload()
  await expect(visitor.getByRole('heading', { name: title, exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '公告修改歷史', exact: true }).click()
  await expect(page.locator('.announcement-workspace li')).toHaveCount(3)
  await context.close()
})
